version: 2
updates:
  - package-ecosystem: npm
    directory: /web-frontend
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      frontend-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: npm
    directory: /web-backend
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      backend-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      codeql-action:
        patterns: ["github/codeql-action/*"]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:45"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
